#!/usr/bin/env python3
"""
Generate the CROSS-TEAM meta-orchestrator command family at ~/.claude/commands/:

    SI.md               meta-dispatcher
    SI-Orchestrate.md   two-stage cross-team selection + approval gate
    SI-<Verb>.md        15 all-teams action verbs (call /SI-Orchestrate first)

Reads the meta-registry (superintelligence/registry.json) LIVE at runtime, so teams
auto-join the panel the moment their `built` flag flips — no regen needed.

Design: superintelligence/META-ORCHESTRATOR-DESIGN.md
Locked: full /SI family + CoCo-hosted; auto-delegate on single-domain; pure-proportional budget.

Usage:  python3 superintelligence/scripts/build_meta_commands.py
"""
import os, pathlib

# REPO is the directory that CONTAINS `superintelligence/` — derived from this file's location
# (this file lives at <REPO>/superintelligence/scripts/build_meta_commands.py) so generated bodies
# reference the user's actual checkout. Overridable via COCO_SI_REPO.
REPO = os.environ.get("COCO_SI_REPO") or str(pathlib.Path(__file__).resolve().parents[2])
# Output dir: honor COCO_SI_COMMANDS_DIR (set by the installer/adapter), else ~/.claude/commands.
OUT = pathlib.Path(os.environ.get("COCO_SI_COMMANDS_DIR") or os.path.expanduser("~/.claude/commands"))
META_REGISTRY = f"{REPO}/superintelligence/registry.json"

# verb title -> (one-line desc, verb-specific output shape)
VERBS = {
    "Analyse":      ("multi-team analysis of a topic", "Per-persona reads grouped by team; synthesis names the strongest cross-team signal and where teams agree/diverge."),
    "Decide":       ("cross-team decision matrix (primary verb)", "Decision matrix: options × personas(team) × verdict. Final recommendation + named dissent, explicitly flagging where one team's lens overrides another's."),
    "Review":       ("multi-team critique of a doc/PR/design", "Findings per persona classified CRITICAL/MAJOR/MINOR/SUGGESTION, tagged by team; ship verdict."),
    "Re-Analyse":   ("re-run a prior analysis with new evidence", "Diff old vs new conclusion; inherit prior cross-team roster unless redlined."),
    "Pre-Mortem":   ("imagine it shipped and failed — why?", "Top failure modes ranked × persona(team) who surfaced each; cross-team blind spots highlighted; early-warning signals; mitigations."),
    "Post-Mortem":  ("root-cause analysis of a failure", "Per-persona 5 Whys (tagged by team) + cross-team synthesis of most-likely root cause + remediation."),
    "Full-Cycle":   ("compound: Review → Analyse → mitigate → Decide → finalize", "Chains the meta verbs as real invocations; each step re-orchestrates across teams; finalized action plan with per-step cross-team attribution."),
    "Tradeoff":     ("side-by-side A-vs-B across teams", "Dimensions × options table; each row carries the team lens; aggregate verdict + most-opposed team named."),
    "Plan":         ("phased plan synthesis", "Phased plan; each phase has an owner persona(team) + dissenting voices from other teams."),
    "Design":       ("architecture/feature design pass", "Component-level decisions attributed to persona(team); cross-team constraints (cost, risk, UX) made explicit."),
    "Vote":         ("yes/no per persona across teams", "Every selected persona casts yes/no + one-sentence rationale; tally by team and overall."),
    "Debug":        ("multi-lens diagnosis", "Each persona hypothesizes a cause (tagged by team); ranked by likelihood; diagnostic test order."),
    "Stress-Test":  ("adversarial cross-team review", "Each persona attacks the proposal from its team's angle; severity matrix; SHIP / HARDEN-THEN-SHIP / REFRAME / DO-NOT-SHIP."),
    "Defend":       ("steelman a position", "Sharpen the claim; load-bearing cited claims; defuse strongest counter-objections (including from opposing teams); 'what would change my mind'."),
    "Roast":        ("blunt cross-team critique", "One cutting line per persona (tagged by team); the single line that hurt most; convergent cross-team critique."),
}

ORCHESTRATE = f"""# /SI-Orchestrate — pick 16-32 personas ACROSS all built teams

> Cross-team meta-orchestrator. Generated by `build_meta_commands.py` — edit the generator, not this file.
> Design: `{REPO}/superintelligence/META-ORCHESTRATOR-DESIGN.md`

## Flags
- `--deep` — full output. `--teams <a,b,...>` — force-scope to these teams (skip Stage A).
- `--no-orchestrate` — use all personas of the auto-selected teams. `--coco-off` — standalone (skip CoCo).
- `--debate` — after selecting the panel, run it as reacting ROUNDS (Step 11) and return the converged positions + transcript, not just the roster. `--debate=full` — one subagent per persona per round (high-stakes only).

## Step 0 — Route via CoCo (when active)
Unless `--coco-off` or `~/.coco/disabled` exists: hand the prompt + recent conversation context to CoCo and ask it to run the two-stage cross-team selection below. CoCo's context makes the team+persona pick sharper. Otherwise run standalone exactly as below.

## Stage A — Team + cell routing (LIGHT — do not read persona files yet)
1. Read `{META_REGISTRY}`. Consider only teams with `built: true`.
2. For each built team, read ONLY its `{REPO}/superintelligence/<dir>/registry.json` `cells` section (cell id + description + count) and the team `description`. Do NOT load persona records yet.
3. **Route (PREFERRED — deterministic, local):** run `python3 {REPO}/superintelligence/scripts/meta_select.py "<prompt>"`. It embeds the prompt vs each built team's profile + cells via local nomic-embed and returns JSON `{{teams:[{{team_id,short,score,weight,cells}}], delegate, delegate_team}}` — use `score` as `team_relevance`, `weight` for the budget split, and `cells` as the candidate cells. If the script/endpoint is unavailable, FALL BACK to keyword overlap of the prompt with team + cell descriptions → `team_relevance` in [0,1].
4. Select the top 1-4 teams above the relevance floor (meta_select already applies it); mark candidate cells within each.
   - **Auto-delegate (LOCKED):** if exactly one team dominates (clear margin), STOP and invoke that team's `/SI-<Team>-Orchestrate "<prompt>"` instead — this is single-domain; no cross-team panel.

## Stage B — Persona selection (scoped to chosen teams only)
5. For the selected teams/cells, load those personas' records from each team registry's `personas` section (slug, cell, domains, voice_style_excerpt, productive_conflict_with).
6. **Budget (LOCKED: pure proportional):** split the 16-32 total across selected teams strictly in proportion to `team_relevance` (no per-team floor; a minor team may get 1-2 seats). Keep the global 16-32 band.
7. Within each team's share, greedy pick by `0.40·domain-match + 0.30·cell-coverage + 0.30·productive-conflict-pairing`, re-scoring after each pick.
8. **Cross-team tension pass:** ensure the panel spans opposing domain lenses (ship/growth/capability ↔ risk/cost/governance/usability). If it collapsed onto one stance, swap in an opposing-domain persona. **Dedupe cross-listed personas by slug** (attribute to `home_team`).

## Step 9 — Approval gate (confidence-tiered)
Present the panel GROUPED BY TEAM, each persona one-line rationale + team tag.
- HIGH confidence → 1-line summary + auto-proceed ("reply 'edit' to redline").
- LOW → AskUserQuestion: Approve / Drop / Add / Re-pick / Reject. Enforce 16-32 (out-of-band → confirm).

## Step 10 — Return
Emit `APPROVED_ROSTER:` one `team:slug` per line for the calling verb. No caching — re-pick every invocation. If `--debate` is NOT set, stop here; the calling verb runs its single-pass output.

## Step 11 — Deliberate (ONLY when `--debate`)
Convene the approved roster as reacting rounds so positions can actually move, then hand the converged result to the calling verb. This is the one home for the round protocol — verbs do not redefine it.
- `--debate` (light): you, the running session, voice all personas across the rounds in-context. Cheap, no subagents.
- `--debate=full`: spawn ONE subagent per persona per round (real independence + web research). At 16-32 personas this is many runs — high-stakes only.

1. **Round 1 — independent positions.** Each persona states: Position (1-2 sentences) · Reasoning (tied to cited stances) · one Open question routed `[for: <slug|anyone>]`. No reacting yet.
2. **Route by productive conflict (NOT all-to-all).** You already scored `productive_conflict_with` during selection (Stage B step 7) — reuse it. Each persona reacts ONLY to (a) the on-panel slugs in its `productive_conflict_with` and (b) anyone who routed a question to it. Never all 16-32 — this bounds the debate and lands the friction where the roster was designed to clash.
3. **React rounds.** Each persona returns: Stance change (`held | sharpened | updated | conceded | hardened`, plus one line on what moved) · Reaction engaging its counterparts BY NAME · Position (now). A concession is a real outcome, not a failure.
4. **Convergence check.** Stop when no persona's stance change is `updated/conceded/hardened` (positions stable) AND no open question another persona could answer remains. Hard cap 4 rounds (Round 1 + up to 3 react rounds); always run at least one react round. State the round count and why you stopped.

Hand the calling verb the converged per-persona positions + a condensed round-by-round transcript. The verb shapes them into its output and reports genuine splits rather than forcing a winner.

ARGUMENTS: {{{{ARGUMENTS}}}}
"""

DISPATCH = f"""# /SI — Super Intelligence meta-dispatcher (all teams)

> Cross-team entry point. Generated by `build_meta_commands.py`.

## Step 1 — Read the meta-registry
Read `{META_REGISTRY}`. List teams with `built: true` (name, persona/cell counts) and the planned ones.

## Routing
- **No args** → print the built-team roster + the cross-team verb list below + usage.
- **First token is a TEAM** (ai/engineering/product-design/finance/…) → tell the user to use that team's scoped commands `/SI-<Team>-*` (e.g. `/SI-AI-Decide`).
- **First token is a VERB** (Decide/Tradeoff/Pre-Mortem/…) → route to `/SI-<Verb>`.
- **Free-text prompt, no verb** → infer the best verb from the prompt (default `/SI-Decide`), confirm in one line, then run it.

## Cross-team verbs
`/SI-Orchestrate` (selection) · Action: {" · ".join("/SI-" + v for v in VERBS)}

## Notes
- Cross-team verbs assemble a panel ACROSS teams via `/SI-Orchestrate` (two-stage, light). Single-domain prompts auto-delegate to one team.
- Per-team scoped commands `/SI-<Team>-*` remain for when you already know the domain.
- CoCo's natural-language router may invoke these directly.

ARGUMENTS: {{{{ARGUMENTS}}}}
"""

# Verbs where a reacting multi-round debate adds value (positions can move through argument).
# Vote (binary by design) and Roast (one cutting line each, no reaction) are intentionally excluded.
DEBATE_VERBS = {
    "Analyse", "Decide", "Review", "Re-Analyse", "Pre-Mortem", "Post-Mortem",
    "Full-Cycle", "Tradeoff", "Plan", "Design", "Stress-Test", "Defend", "Debug",
}

DELIBERATION_BLOCK = """
## Step 2.5 — Use the deliberation (only when `--debate`)
When `--debate` is set, the reacting rounds run inside `/SI-Orchestrate` (its Step 11 Deliberate: independent positions → route by `productive_conflict_with` → react rounds with stance changes → convergence, hard cap 4 rounds). Consume the converged per-persona positions and the round transcript it returns here, instead of a single one-shot pass. The protocol lives there, not in this verb.
"""

SPLIT_CLAUSE = """
When `--debate` ran, map the deliberation honestly: **Consensus** · **Unresolved disagreements** (who holds what, and WHY it didn't resolve) · **Open questions for the user** · **Verdict**. If the panel genuinely split, write **SPLIT** with 2-3 decision criteria instead of forcing a winner — an honest split beats false confidence. Also give a condensed round-by-round transcript (per persona: position + what moved) so the verdict is auditable.
"""


def verb_body(title, desc, shape, debate=False):
    chain = title == "Full-Cycle"
    flags = "- `--deep` (full output) · `--teams <a,b,...>` (force team scope) · `--no-orchestrate` · `--coco-off`"
    if debate:
        flags += "\n- `--debate` (run the panel as reacting ROUNDS, not one pass) · `--debate=full` (one subagent per persona per round — high-stakes only)"
    deliberation = DELIBERATION_BLOCK if debate else ""
    split_clause = SPLIT_CLAUSE if debate else ""
    if debate:
        step1 = ("Invoke `/SI-Orchestrate \"<prompt>\"`, forwarding `--debate`/`--debate=full` when set "
                 "(unless `--no-orchestrate`/`--teams`/`--personas`). Capture `APPROVED_ROSTER` (each entry is `team:slug`); "
                 "when `--debate` ran, also capture the converged deliberation (positions + transcript) it returns. "
                 "Single-domain prompts will auto-delegate to one team's orchestrator — honor that.")
    else:
        step1 = ("Invoke `/SI-Orchestrate \"<prompt>\"` (unless `--no-orchestrate`/`--teams`/`--personas`). "
                 "Capture `APPROVED_ROSTER` (each entry is `team:slug`). "
                 "Single-domain prompts will auto-delegate to one team's orchestrator — honor that.")
    return f"""# /SI-{title} — all-teams {desc}

> Cross-team action verb. Orchestrated through CoCo. Generated by `build_meta_commands.py`.

## Flags
{flags}

## Step 1 — Cross-team orchestrate
{step1}

## Step 2 — Read the approved personas
For each `team:slug`, read `{REPO}/superintelligence/<team-dir>/personas/<slug>.md` (resolve `<team-dir>` from the meta-registry). Channel each persona via signature_moves + mental_models + voice_style.
{deliberation}
## Step 3 — {title} output
{shape}
{split_clause}{"Chain each sub-step as a real `/SI-<step>` invocation; re-orchestrate per step (teams may differ)." if chain else ""}

## Attribution (mandatory)
Every claim cites **persona + team** — e.g. *Aswath Damodaran (Finance)*. Synthesis MUST surface cross-team disagreement explicitly, not just within-team. No "the panel said."

## Conventions
Registry is source of truth (re-read each run; no cache). Full English prose. Every cited stance traces to the persona's `public_stances`/`recent_signal_12mo`.

ARGUMENTS: {{{{ARGUMENTS}}}}
"""

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    files = {"SI.md": DISPATCH, "SI-Orchestrate.md": ORCHESTRATE}
    for title, (desc, shape) in VERBS.items():
        files[f"SI-{title}.md"] = verb_body(title, desc, shape, debate=title in DEBATE_VERBS)
    for name, body in files.items():
        (OUT / name).write_text(body, encoding="utf-8")
    print(f"Wrote {len(files)} meta-orchestrator command files to {OUT}:")
    print("  " + ", ".join(sorted(files)))

if __name__ == "__main__":
    main()
