#!/usr/bin/env python3
"""
Team-generic validator sweep. Validates every built persona (HTTP-resolves URLs +
quota/citation/slug checks via a team's validate_persona.validate) and writes
<team>/VALIDATION.md with PASS / NEEDS-TOPUP.

Run from the repo root with team directory names:

    python3 superintelligence/scripts/validate_all_generic.py finance trading
    python3 superintelligence/scripts/validate_all_generic.py --all

Also still works as a drop-in copied to superintelligence/<team>/scripts/ with no
arguments (the original deployment mode).
"""
from __future__ import annotations
import json, sys, pathlib

HERE = pathlib.Path(__file__).resolve().parent
CUTOFF = "2025-06-01"  # 12-months-ago window for recent_signal_12mo (matches build_local)


def find_validate(team_dir: pathlib.Path, si_root: pathlib.Path):
    """Import validate() from the team's own scripts dir, falling back to any
    team that ships validate_persona.py (the module is team-independent)."""
    candidates = [team_dir / "scripts"]
    candidates += sorted(p.parent for p in si_root.glob("*/scripts/validate_persona.py"))
    for c in candidates:
        if (c / "validate_persona.py").exists():
            sys.path.insert(0, str(c))
            try:
                from validate_persona import validate  # noqa: PLC0415
                return validate
            finally:
                sys.path.remove(str(c))
    sys.exit(f"validate_persona.py not found under {si_root}/*/scripts/")


def roster_slugs(team_dir: pathlib.Path) -> list[str]:
    roster = json.loads((team_dir / "roster.json").read_text())
    persons = roster.get("personas", [])
    if isinstance(persons, dict):
        slugs = list(persons.keys())
    else:
        slugs = [p["slug"] if isinstance(p, dict) else p for p in persons]
    return slugs + [x["slug"] for x in roster.get("cross_listed", [])]


def sweep(team_dir: pathlib.Path, validate) -> None:
    team = team_dir.name
    pers = team_dir / "personas"
    slugs = roster_slugs(team_dir)
    files = sorted(pers.glob("*.md"))
    rows, npass, ntop, topup = [], 0, 0, []
    for f in files:
        try:
            verdict, reasons, n, ok = validate(f, slugs, CUTOFF)  # (verdict, reasons, total_urls, ok_count)
        except Exception as e:
            verdict, reasons, n, ok = "NEEDS-TOPUP", [f"validator crash: {type(e).__name__}: {e}"], 0, 0
        if verdict == "PASS":
            npass += 1
        else:
            ntop += 1
            topup.append(f.stem)
        rows.append(f"| `{f.stem}` | {verdict} | {ok}/{n} | {'; '.join(reasons)[:120]} |")
    total = len(files)
    report = f"""# {team} — validation sweep

Generated by `validate_all_generic.py`. {npass}/{total} PASS, {ntop} NEEDS-TOPUP.
Personas are illustrative composites of real public figures (see DISCLAIMER.md);
the verify-gate confirms every cited URL resolves and quotas/citations hold.

## NEEDS-TOPUP ({ntop})

{(chr(10).join('- `' + s + '`' for s in topup)) if topup else '- none'}

## Full results

| Slug | Verdict | URLs ok | Notes |
|---|---|---|---|
{chr(10).join(rows)}
"""
    (team_dir / "VALIDATION.md").write_text(report, encoding="utf-8")
    print(f"{team}: {npass}/{total} PASS, {ntop} NEEDS-TOPUP -> {team_dir / 'VALIDATION.md'}")
    if topup:
        print("NEEDS-TOPUP: " + " ".join(topup))


def main() -> None:
    args = sys.argv[1:]
    if HERE.parent.name != "superintelligence" and not args:
        # drop-in mode: this file lives at superintelligence/<team>/scripts/
        team_dir = HERE.parent
        si_root = team_dir.parent
        teams = [team_dir]
    else:
        si_root = HERE.parent
        if args == ["--all"] or not args:
            teams = sorted(d for d in si_root.iterdir() if (d / "roster.json").exists())
        else:
            teams = [si_root / a for a in args]
            for t in teams:
                if not (t / "roster.json").exists():
                    sys.exit(f"No roster.json in {t}")
    for t in teams:
        sweep(t, find_validate(t, si_root))


if __name__ == "__main__":
    main()
