#!/usr/bin/env python3
"""
Team-generic validator sweep. Drop into superintelligence/<team>/scripts/ and run.
Validates every built persona (HTTP-resolves URLs + quota/citation/slug checks via the
local validate_persona.validate) and writes <team>/VALIDATION.md with PASS / NEEDS-TOPUP.

    python3 superintelligence/<team>/scripts/validate_all.py
"""
from __future__ import annotations
import json, sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from validate_persona import validate

TEAM_DIR = pathlib.Path(__file__).resolve().parents[1]
TEAM = TEAM_DIR.name
PERS = TEAM_DIR / "personas"
ROSTER = json.loads((TEAM_DIR / "roster.json").read_text())
SLUGS = [p["slug"] for p in ROSTER["personas"]] + [x["slug"] for x in ROSTER.get("cross_listed", [])]
CUTOFF = "2025-06-01"  # 12-months-ago window for recent_signal_12mo (matches build_local)


def main():
    files = sorted(PERS.glob("*.md"))
    rows, npass, ntop = [], 0, 0
    topup = []
    for f in files:
        try:
            verdict, reasons, n, ok = validate(f, SLUGS, CUTOFF)  # (verdict, reasons, total_urls, ok_count)
        except Exception as e:
            verdict, reasons, n, ok = "NEEDS-TOPUP", [f"validator crash: {type(e).__name__}: {e}"], 0, 0
        if verdict == "PASS":
            npass += 1
        else:
            ntop += 1
            topup.append(f.stem)
        rows.append(f"| `{f.stem}` | {verdict} | {ok}/{n} | {'; '.join(reasons)[:120]} |")
    total = len(files)
    report = f"""# {TEAM} — validation sweep

Generated by `validate_all.py`. {npass}/{total} PASS, {ntop} NEEDS-TOPUP.
Personas are illustrative composites of real public figures (see DISCLAIMER.md);
the verify-gate confirms every cited URL resolves and quotas/citations hold.

## NEEDS-TOPUP ({ntop})

{(chr(10).join('- `' + s + '`' for s in topup)) if topup else '- none'}

## Full results

| Slug | Verdict | URLs ok | Notes |
|---|---|---|---|
{chr(10).join(rows)}
"""
    (TEAM_DIR / "VALIDATION.md").write_text(report, encoding="utf-8")
    print(f"{TEAM}: {npass}/{total} PASS, {ntop} NEEDS-TOPUP -> {TEAM_DIR/'VALIDATION.md'}")
    if topup:
        print("NEEDS-TOPUP: " + " ".join(topup))


if __name__ == "__main__":
    main()
