#!/usr/bin/env python3
"""Render EVIDENCE.md from EVIDENCE.json, a pure deterministic function.

Exit contract: 0 = pass, 1 = block (rendered file differs from disk), 2 = unrunnable
(repository, run, or EVIDENCE.json unreadable or malformed, including duplicate ids).

Exported for import by other scripts (in particular run_gate.py):

  HEADER: the exact first line every rendered EVIDENCE.md carries.
  render(evidence: dict) -> str: pure function, no wall-clock, deterministic.

CLI:
  render_evidence.py --repo-root PATH
      reads <repo-root>/.team-ship/EVIDENCE.json, writes
      <repo-root>/.team-ship/EVIDENCE.md, appends an artifact-written receipt.
  render_evidence.py --repo-root PATH --check
      re-renders in memory and compares against the file on disk. Any byte
      difference, including whitespace, is exit 1.
  render_evidence.py --self-test
      runs make_fixtures.py, then exercises both modes above against fixtures.
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gate_state


HEADER = "Generated by run_gate.py from EVIDENCE.json. Do not edit; edits are detected."


def _format_value(value: Any) -> str:
    """Render a single field value deterministically."""
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True, separators=(", ", ": "))
    return str(value)


def _entry_sort_key(entry: Dict[str, Any]):
    entry_id = entry.get("id", "")
    digits = "".join(c for c in str(entry_id) if c.isdigit())
    numeric = int(digits) if digits else 0
    return (numeric, str(entry_id))


def render(evidence: Dict[str, Any]) -> str:
    """Render EVIDENCE.md text from a parsed EVIDENCE.json object.

    Pure function: same input always yields the same output. Every timestamp
    that appears comes from the evidence content itself, never from the clock.
    """
    lines = [HEADER, ""]
    lines.append("# Ship Evidence")
    lines.append("")
    lines.append(f"Run: {evidence.get('runId', 'unknown')}")
    lines.append(f"Head: {evidence.get('head', 'unknown')}")
    lines.append("")

    entries = evidence.get("entries", [])
    if not isinstance(entries, list):
        entries = []

    for entry in sorted(entries, key=_entry_sort_key):
        entry_id = entry.get("id", "?")
        label = entry.get("label", "")
        gate = entry.get("gate", "?")
        lines.append(f"## {entry_id}: {label} (gate {gate})")
        for key in sorted(entry.keys()):
            if key in ("id", "label", "gate"):
                continue
            lines.append(f"- {key}: {_format_value(entry[key])}")
        lines.append("")

    text = "\n".join(lines).rstrip("\n") + "\n"
    return text


def _git_head(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"not a git repository: {repo_root}")
    return result.stdout.strip()


def _check_duplicate_ids(evidence: Dict[str, Any]) -> None:
    """Raise if two entries in EVIDENCE.json share an id (silent last-wins otherwise)."""
    seen = set()
    for entry in evidence.get("entries", []):
        if not isinstance(entry, dict):
            continue
        entry_id = entry.get("id")
        if entry_id is None:
            continue
        if entry_id in seen:
            raise RuntimeError(f"EVIDENCE.json malformed: duplicate id {entry_id}")
        seen.add(entry_id)


def _load_evidence(repo_root: Path) -> Dict[str, Any]:
    evidence_path = repo_root / ".team-ship" / "EVIDENCE.json"
    if not evidence_path.is_file():
        raise RuntimeError(f"EVIDENCE.json not found at {evidence_path}")
    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise RuntimeError(f"EVIDENCE.json is not valid JSON: {evidence_path}: {e}")
    _check_duplicate_ids(evidence)
    return evidence


def cmd_render(repo_root: str) -> int:
    """Default mode: render EVIDENCE.md from EVIDENCE.json and write it."""
    root = Path(repo_root).resolve()

    try:
        _git_head(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    run_dir = gate_state.find_run(root)
    if run_dir is None:
        print(f"ERROR: no active run found under {root}", file=sys.stderr)
        return 2

    try:
        evidence = _load_evidence(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    text = render(evidence)
    md_path = root / ".team-ship" / "EVIDENCE.md"
    md_path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    tmp_path = md_path.with_name(md_path.name + ".tmp")
    tmp_path.write_bytes(data)
    os.replace(str(tmp_path), str(md_path))

    sha256 = hashlib.sha256(data).hexdigest()
    lines_count = text.count("\n")
    try:
        gate_state.append_receipt(
            run_dir, "artifact-written",
            {"path": ".team-ship/EVIDENCE.md", "sha256": sha256, "lines": lines_count}
        )
    except Exception as e:
        md_path.unlink(missing_ok=True)
        print(f"ERROR: failed to record artifact-written receipt: {e}", file=sys.stderr)
        return 2

    return 0


def cmd_check(repo_root: str) -> int:
    """--check mode: re-render in memory and compare against the file on disk."""
    root = Path(repo_root).resolve()

    try:
        _git_head(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    run_dir = gate_state.find_run(root)
    if run_dir is None:
        print(f"ERROR: no active run found under {root}", file=sys.stderr)
        return 2

    try:
        evidence = _load_evidence(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    md_path = root / ".team-ship" / "EVIDENCE.md"
    if not md_path.is_file():
        print(f"ERROR: EVIDENCE.md not found at {md_path}", file=sys.stderr)
        return 2

    try:
        on_disk = md_path.read_text(encoding="utf-8")
    except OSError as e:
        print(f"ERROR: EVIDENCE.md unreadable: {e}", file=sys.stderr)
        return 2

    current = render(evidence)
    if current == on_disk:
        return 0

    print("ERROR: EVIDENCE.md differs from the render of EVIDENCE.json", file=sys.stderr)
    current_lines = current.splitlines()
    disk_lines = on_disk.splitlines()
    for i in range(max(len(current_lines), len(disk_lines))):
        a = disk_lines[i] if i < len(disk_lines) else "<missing>"
        b = current_lines[i] if i < len(current_lines) else "<missing>"
        if a != b:
            print(f"line {i + 1}:", file=sys.stdout)
            print(f"- {a!r}", file=sys.stdout)
            print(f"+ {b!r}", file=sys.stdout)
            break
    return 1


def _self_test_fixture_dir() -> Path:
    return Path(__file__).resolve().parent / "fixtures" / "claim_evidence"


def _ensure_fixtures() -> int:
    fixture_dir = _self_test_fixture_dir()
    make_fixtures = fixture_dir / "make_fixtures.py"
    if not make_fixtures.is_file():
        print(f"ERROR: make_fixtures.py not found at {make_fixtures}", file=sys.stderr)
        return 2
    result = subprocess.run([sys.executable, str(make_fixtures)], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR: make_fixtures.py failed: {result.stderr}", file=sys.stderr)
        return 2
    return 0


def cmd_self_test() -> int:
    """Run this script's CLI, as a subprocess, against fixture repositories."""
    rc = _ensure_fixtures()
    if rc != 0:
        return rc

    fixture_dir = _self_test_fixture_dir()

    # (fixture_name, build_from, extra_setup, args, expected_exit, stderr_contains)
    cases = [
        ("all-claims-backed", "all-claims-backed", None, ["--check"], 0, None),
        ("hand-edited-evidence-md", "hand-edited-evidence-md", None, ["--check"], 1, "differs"),
        ("whitespace-edited-evidence-md", "whitespace-edited-evidence-md", None, ["--check"], 1, "differs"),
        ("missing-evidence-json", "all-claims-backed", "delete-evidence-json", [], 2, "EVIDENCE.json not found"),
    ]

    all_pass = True

    for name, build_from, extra_setup, args, expected_exit, stderr_contains in cases:
        build_dir = fixture_dir / build_from / "_build"
        if not build_dir.is_dir():
            print(f"{name}: FIXTURE NOT FOUND", file=sys.stderr)
            all_pass = False
            continue

        with tempfile.TemporaryDirectory() as tmpdir:
            import shutil
            repo_copy = Path(tmpdir) / "repo"
            shutil.copytree(build_dir, repo_copy)

            state_root = Path(tmpdir) / "state"
            state_root.mkdir()
            os.environ["TEAM_STATE_ROOT"] = str(state_root)

            try:
                gate_state.start_run(str(repo_copy), "test", [])
            except Exception as e:
                print(f"{name}: FAIL - could not start run: {e}", file=sys.stderr)
                all_pass = False
                continue

            if extra_setup == "delete-evidence-json":
                (repo_copy / ".team-ship" / "EVIDENCE.json").unlink()

            result = subprocess.run([sys.executable, __file__, "--repo-root", str(repo_copy)] + args,
                capture_output=True, text=True, timeout=30
            )

            if result.returncode != expected_exit:
                print(
                    f"{name}: expected {expected_exit} got {result.returncode} FAIL",
                    file=sys.stderr
                )
                if result.stderr:
                    print(f"  stderr: {result.stderr}", file=sys.stderr)
                all_pass = False
                continue

            if stderr_contains and stderr_contains not in result.stderr:
                print(
                    f"{name}: expected {expected_exit} got {expected_exit} FAIL "
                    f"(stderr missing {stderr_contains!r})",
                    file=sys.stderr
                )
                print(f"  got: {result.stderr}", file=sys.stderr)
                all_pass = False
                continue

            print(f"{name}: expected {expected_exit} got {expected_exit} OK")

    return 0 if all_pass else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repository root")
    parser.add_argument("--check", action="store_true", help="Compare rendered output to disk")
    parser.add_argument("--self-test", action="store_true", help="Run self-tests")
    args = parser.parse_args()

    if args.self_test:
        return cmd_self_test()

    try:
        if args.check:
            return cmd_check(args.repo_root)
        return cmd_render(args.repo_root)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
