#!/usr/bin/env python3
"""Render the quantitative section of a PR body from EVIDENCE.json.

Exit contract: 0 = pass, 2 = unrunnable (repository, run, or EVIDENCE.json
unreadable or malformed, including duplicate ids). There is no block outcome
for this script; a missing narrative file is not an error, since the
narrative is optional model-written prose.

Every generated sentence carries its own [E<n>] tag, resolved directly from
EVIDENCE.json entries; the model writes only the narrative section above it.
If an override receipt exists in the run, the override text is rendered
verbatim in its own fenced section, using a fence one backtick longer than
the longest backtick run inside the text (minimum three), which keeps the
text inert regardless of what markup or code fences it itself contains.

CLI:
  render_pr_body.py --repo-root PATH [--narrative FILE]
  render_pr_body.py --self-test
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gate_state


HEADER = "Generated by render_pr_body.py from EVIDENCE.json. Do not edit."


def _git_head(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"not a git repository: {repo_root}")
    return result.stdout.strip()


def _check_duplicate_ids(evidence: Dict[str, Any]) -> None:
    """Raise if two entries in EVIDENCE.json share an id (silent last-wins otherwise)."""
    seen = set()
    for entry in evidence.get("entries", []):
        if not isinstance(entry, dict):
            continue
        entry_id = entry.get("id")
        if entry_id is None:
            continue
        if entry_id in seen:
            raise RuntimeError(f"EVIDENCE.json malformed: duplicate id {entry_id}")
        seen.add(entry_id)


def _load_evidence(repo_root: Path) -> Dict[str, Any]:
    evidence_path = repo_root / ".team-ship" / "EVIDENCE.json"
    if not evidence_path.is_file():
        raise RuntimeError(f"EVIDENCE.json not found at {evidence_path}")
    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise RuntimeError(f"EVIDENCE.json is not valid JSON: {evidence_path}: {e}")
    _check_duplicate_ids(evidence)
    return evidence


def _entry_sort_key(entry: Dict[str, Any]):
    entry_id = entry.get("id", "")
    digits = "".join(c for c in str(entry_id) if c.isdigit())
    numeric = int(digits) if digits else 0
    return (numeric, str(entry_id))


def _sentence_for(entry: Dict[str, Any]) -> str:
    """Build one deterministic, tagged sentence from an EVIDENCE.json entry."""
    entry_id = entry.get("id", "?")
    if "passed" in entry:
        passed = entry.get("passed", 0)
        failed = entry.get("failed", 0)
        skipped = entry.get("skipped", 0)
        return f"{passed} passed, {failed} failed, {skipped} skipped. [{entry_id}]"
    if "coverage" in entry:
        return f"Coverage is {entry['coverage']}%. [{entry_id}]"
    if "tool" in entry:
        tool = entry["tool"]
        exit_code = entry.get("exit", 0)
        if exit_code == 0:
            return f"{tool} clean. [{entry_id}]"
        return f"{tool} exit {exit_code}. [{entry_id}]"
    label = entry.get("label", "gate")
    return f"{label} exit {entry.get('exit', '?')}. [{entry_id}]"


def _find_overrides(run_dir: Path) -> List[tuple]:
    """Scan receipts.jsonl for every override receipt and return them in receipt
    order as (gate, instruction, by) tuples.

    Reads detail.instruction, the shape every writer records (the turn-log hook
    and the aggregators' documented override receipt), falling back to
    detail.reason for older receipts. Returns an empty list when none exist.
    """
    receipts_file = run_dir / "receipts.jsonl"
    if not receipts_file.is_file():
        return []
    override_list: List[tuple] = []
    for line in receipts_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue
        if record.get("kind") == "override":
            detail = record.get("detail", {})
            if isinstance(detail, dict):
                instruction = detail.get("instruction") or detail.get("reason", "")
                gate = detail.get("gate", "unknown")
                by = detail.get("by", "unknown")
                override_list.append((gate, instruction, by))
    return override_list


def _fence_for(text: str) -> str:
    """Return a backtick fence one longer than the longest run inside text."""
    longest = 0
    for match in re.finditer(r"`+", text):
        longest = max(longest, len(match.group(0)))
    return "`" * max(3, longest + 1)


def render_pr_body(evidence: Dict[str, Any], narrative: str, overrides: List[tuple]) -> str:
    """Pure function: narrative plus a generated results section plus one
    verbatim fenced block per override receipt, in receipt order, each fenced
    with one more backtick than the longest run inside its text."""
    lines = []
    if narrative.strip():
        lines.append(narrative.rstrip("\n"))
        lines.append("")

    lines.append(HEADER)
    lines.append("")
    lines.append("## Results")
    lines.append("")

    entries = evidence.get("entries", [])
    if not isinstance(entries, list):
        entries = []
    for entry in sorted(entries, key=_entry_sort_key):
        lines.append(f"- {_sentence_for(entry)}")

    if overrides:
        lines.append("")
        lines.append("## Overrides" if len(overrides) > 1 else "## Override")
        lines.append("")
        for gate, instruction, by in overrides:
            lines.append(f"Override for gate {gate} by {by}:")
            lines.append("")
            fence = _fence_for(instruction)
            lines.append(fence)
            lines.append(instruction.rstrip("\n"))
            lines.append(fence)
            lines.append("")

    text = "\n".join(lines).rstrip("\n") + "\n"
    return text


def cmd_render(repo_root: str, narrative_path: Optional[str]) -> int:
    root = Path(repo_root).resolve()

    try:
        _git_head(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    try:
        run_dir = gate_state.find_run(root)
    except gate_state.RunMarkerUnreadable as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if run_dir is None:
        print(f"ERROR: no active run found under {root}", file=sys.stderr)
        return 2

    try:
        evidence = _load_evidence(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    narrative = ""
    if narrative_path:
        narrative_file = Path(narrative_path)
    else:
        narrative_file = root / ".team-ship" / "PR-NARRATIVE.md"
    if narrative_file.is_file():
        narrative = narrative_file.read_text(encoding="utf-8")

    overrides = _find_overrides(run_dir)

    text = render_pr_body(evidence, narrative, overrides)
    body_path = root / ".team-ship" / "PR-BODY.md"
    body_path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    tmp_path = body_path.with_name(body_path.name + ".tmp")
    tmp_path.write_bytes(data)
    os.replace(str(tmp_path), str(body_path))

    sha256 = hashlib.sha256(data).hexdigest()
    lines_count = text.count("\n")
    try:
        gate_state.append_receipt(
            run_dir, "artifact-written",
            {"path": ".team-ship/PR-BODY.md", "sha256": sha256, "lines": lines_count}
        )
    except Exception as e:
        body_path.unlink(missing_ok=True)
        print(f"ERROR: failed to record artifact-written receipt: {e}", file=sys.stderr)
        return 2

    return 0


def _self_test_fixture_dir() -> Path:
    return Path(__file__).resolve().parent / "fixtures" / "claim_evidence"


def _ensure_fixtures() -> int:
    fixture_dir = _self_test_fixture_dir()
    make_fixtures = fixture_dir / "make_fixtures.py"
    if not make_fixtures.is_file():
        print(f"ERROR: make_fixtures.py not found at {make_fixtures}", file=sys.stderr)
        return 2
    result = subprocess.run([sys.executable, str(make_fixtures)], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR: make_fixtures.py failed: {result.stderr}", file=sys.stderr)
        return 2
    return 0


OVERRIDE_MARKUP_TEXT = "Ship with **bold** markup and <script>alert(1)</script> intact, per Rijul, 2026-09-17."
OVERRIDE_BACKTICKS_TEXT = "Override reason includes a fenced block:\n```\nsome code\n```\nper Rijul, 2026-09-17."
OVERRIDE_GATE_10_TEXT = "Override for coverage gate per requirement R7."
OVERRIDE_GATE_ARCH_TEXT = "Override for architecture gate, superseded by discussion."


def cmd_self_test() -> int:
    rc = _ensure_fixtures()
    if rc != 0:
        return rc

    fixture_dir = _self_test_fixture_dir()

    # (name, build_from, override_receipts_or_None, expected_exit, required_substrings)
    # override_receipts_or_None is a list of receipt detail dicts appended in order,
    # in the real shape {gate, instruction, by}, or {reason} for the old shape.
    cases = [
        ("all-claims-backed", "all-claims-backed", None, 0, ["```"]),
        ("override-with-markup", "override-with-markup",
         [{"gate": "approval", "instruction": OVERRIDE_MARKUP_TEXT, "by": "user"}], 0, ["```", OVERRIDE_MARKUP_TEXT]),
        ("override-with-backticks", "override-with-backticks",
         [{"gate": "approval", "instruction": OVERRIDE_BACKTICKS_TEXT, "by": "user"}], 0, ["````", OVERRIDE_BACKTICKS_TEXT.rstrip("\n")]),
        ("override-old-shape", "override-with-markup",
         [{"reason": OVERRIDE_MARKUP_TEXT}], 0, ["```", OVERRIDE_MARKUP_TEXT]),
        ("override-two-gates", "override-with-markup",
         [{"gate": "10", "instruction": OVERRIDE_GATE_10_TEXT, "by": "user"},
          {"gate": "arch", "instruction": OVERRIDE_GATE_ARCH_TEXT, "by": "user"}], 0,
         ["## Overrides", "Override for gate 10 by user", OVERRIDE_GATE_10_TEXT,
          "Override for gate arch by user", OVERRIDE_GATE_ARCH_TEXT]),
    ]

    all_pass = True

    for name, build_from, override_receipts, expected_exit, required_substrings in cases:
        build_dir = fixture_dir / build_from / "_build"
        if not build_dir.is_dir():
            print(f"{name}: FIXTURE NOT FOUND", file=sys.stderr)
            all_pass = False
            continue

        with tempfile.TemporaryDirectory() as tmpdir:
            repo_copy = Path(tmpdir) / "repo"
            shutil.copytree(build_dir, repo_copy)

            state_root = Path(tmpdir) / "state"
            state_root.mkdir()
            os.environ["TEAM_STATE_ROOT"] = str(state_root)

            try:
                run_id = gate_state.start_run(str(repo_copy), "test", [])
            except Exception as e:
                print(f"{name}: FAIL - could not start run: {e}", file=sys.stderr)
                all_pass = False
                continue

            run_dir = state_root / run_id
            if override_receipts is not None:
                try:
                    for override_detail in override_receipts:
                        gate_state.append_receipt(run_dir, "override", override_detail)
                except Exception as e:
                    print(f"{name}: FAIL - could not append override receipt: {e}", file=sys.stderr)
                    all_pass = False
                    continue

            result = subprocess.run([sys.executable, __file__, "--repo-root", str(repo_copy)],
                capture_output=True, text=True, timeout=30
            )

            if result.returncode != expected_exit:
                print(f"{name}: expected {expected_exit} got {result.returncode} FAIL", file=sys.stderr)
                if result.stderr:
                    print(f"  stderr: {result.stderr}", file=sys.stderr)
                all_pass = False
                continue

            body_path = repo_copy / ".team-ship" / "PR-BODY.md"
            body_text = body_path.read_text(encoding="utf-8") if body_path.is_file() else ""

            case_ok = True
            if override_receipts is not None:
                for needle in required_substrings:
                    if needle not in body_text:
                        print(f"{name}: FAIL - {needle[:40]!r} not found in the rendered body", file=sys.stderr)
                        all_pass = False
                        case_ok = False
                        break
                if case_ok and len(override_receipts) > 1:
                    first = body_text.index(override_receipts[0]["instruction"])
                    second = body_text.index(override_receipts[1]["instruction"])
                    if not first < second:
                        print(f"{name}: FAIL - overrides not in receipt order", file=sys.stderr)
                        all_pass = False
                        case_ok = False

            if case_ok:
                print(f"{name}: expected {expected_exit} got {expected_exit} OK")

    return 0 if all_pass else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repository root")
    parser.add_argument("--narrative", default=None, help="Path to the model-written narrative file")
    parser.add_argument("--self-test", action="store_true", help="Run self-tests")
    args = parser.parse_args()

    if args.self_test:
        return cmd_self_test()

    try:
        return cmd_render(args.repo_root, args.narrative)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
