#!/usr/bin/env python3
"""Assemble the five approval-gate artifacts into .team-ship/APPROVAL.md.

Exit contract: 0 = pass, 1 = block (an approval-gate artifact is missing),
2 = unrunnable (repository or run unreadable).

The five artifacts, per team:ship.md's approval gate (Stage 4 to Stage 5):
  RESEARCH-BRIEF.md, ARCHITECTURE-OPTIONS.md, PLAN.md, ARCH-PLAN.json,
  REVIEW-FINDINGS.md, all under .team-ship/.

CLI:
  render_approval.py --repo-root PATH
  render_approval.py --self-test
"""

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gate_state


HEADER = "Generated by render_approval.py from the five approval-gate artifacts. Do not edit."

ARTIFACTS: List[Tuple[str, str]] = [
    ("Research Brief", "RESEARCH-BRIEF.md"),
    ("Architecture Options", "ARCHITECTURE-OPTIONS.md"),
    ("Plan", "PLAN.md"),
    ("Intended Architecture", "ARCH-PLAN.json"),
    ("Review Findings", "REVIEW-FINDINGS.md"),
]


def _git_head(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"not a git repository: {repo_root}")
    return result.stdout.strip()


def _render_arch_plan_table(arch_plan_path: Path) -> str:
    try:
        data = json.loads(arch_plan_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        return f"(ARCH-PLAN.json unreadable: {e})"

    components = data.get("components", [])
    if not isinstance(components, list) or not components:
        return "(no components declared)"

    lines = ["| Component | Status | Intended Paths |", "|---|---|---|"]
    for comp in components:
        title = comp.get("title") or comp.get("id") or "?"
        status = comp.get("status", "?")
        paths = comp.get("intendedPaths", [])
        if not isinstance(paths, list):
            paths = [str(paths)]
        lines.append(f"| {title} | {status} | {', '.join(paths)} |")
    return "\n".join(lines)


def render_approval(repo_root: Path, head: str) -> str:
    """Assemble the five artifacts into one deterministic markdown document."""
    lines = [HEADER, "", "# Approval Gate", "", f"Head: {head}", ""]

    for label, filename in ARTIFACTS:
        path = repo_root / ".team-ship" / filename
        lines.append(f"## {label}")
        lines.append("")
        if filename.endswith(".json"):
            lines.append(_render_arch_plan_table(path))
        else:
            lines.append(path.read_text(encoding="utf-8").rstrip("\n"))
        lines.append("")

    text = "\n".join(lines).rstrip("\n") + "\n"
    return text


def cmd_render(repo_root: str) -> int:
    root = Path(repo_root).resolve()

    try:
        head = _git_head(root)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    try:
        run_dir = gate_state.find_run(root)
    except gate_state.RunMarkerUnreadable as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if run_dir is None:
        print(f"ERROR: no active run found under {root}", file=sys.stderr)
        return 2

    missing = []
    for label, filename in ARTIFACTS:
        path = root / ".team-ship" / filename
        if not path.is_file():
            missing.append(f"{label} ({filename})")

    if missing:
        print(f"ERROR: missing approval artifact(s): {', '.join(missing)}", file=sys.stderr)
        return 1

    text = render_approval(root, head)
    approval_path = root / ".team-ship" / "APPROVAL.md"
    approval_path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    tmp_path = approval_path.with_name(approval_path.name + ".tmp")
    tmp_path.write_bytes(data)
    os.replace(str(tmp_path), str(approval_path))

    sha256 = hashlib.sha256(data).hexdigest()
    lines_count = text.count("\n")
    try:
        gate_state.append_receipt(
            run_dir, "artifact-written",
            {"path": ".team-ship/APPROVAL.md", "sha256": sha256, "lines": lines_count}
        )
    except Exception as e:
        approval_path.unlink(missing_ok=True)
        print(f"ERROR: failed to record artifact-written receipt: {e}", file=sys.stderr)
        return 2

    return 0


def _self_test_fixture_dir() -> Path:
    return Path(__file__).resolve().parent / "fixtures" / "claim_evidence"


def _ensure_fixtures() -> int:
    fixture_dir = _self_test_fixture_dir()
    make_fixtures = fixture_dir / "make_fixtures.py"
    if not make_fixtures.is_file():
        print(f"ERROR: make_fixtures.py not found at {make_fixtures}", file=sys.stderr)
        return 2
    result = subprocess.run([sys.executable, str(make_fixtures)], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR: make_fixtures.py failed: {result.stderr}", file=sys.stderr)
        return 2
    return 0


def cmd_self_test() -> int:
    rc = _ensure_fixtures()
    if rc != 0:
        return rc

    fixture_dir = _self_test_fixture_dir()

    # (name, build_from, expected_exit, stderr_contains)
    cases = [
        ("all-claims-backed", "all-claims-backed", 0, None),
        ("missing-approval-artifact", "missing-approval-artifact", 1, "ARCH-PLAN.json"),
    ]

    all_pass = True

    for name, build_from, expected_exit, stderr_contains in cases:
        build_dir = fixture_dir / build_from / "_build"
        if not build_dir.is_dir():
            print(f"{name}: FIXTURE NOT FOUND", file=sys.stderr)
            all_pass = False
            continue

        with tempfile.TemporaryDirectory() as tmpdir:
            repo_copy = Path(tmpdir) / "repo"
            shutil.copytree(build_dir, repo_copy)

            state_root = Path(tmpdir) / "state"
            state_root.mkdir()
            os.environ["TEAM_STATE_ROOT"] = str(state_root)

            try:
                gate_state.start_run(str(repo_copy), "test", [])
            except Exception as e:
                print(f"{name}: FAIL - could not start run: {e}", file=sys.stderr)
                all_pass = False
                continue

            result = subprocess.run([sys.executable, __file__, "--repo-root", str(repo_copy)],
                capture_output=True, text=True, timeout=30
            )

            if result.returncode != expected_exit:
                print(f"{name}: expected {expected_exit} got {result.returncode} FAIL", file=sys.stderr)
                if result.stderr:
                    print(f"  stderr: {result.stderr}", file=sys.stderr)
                all_pass = False
                continue

            if stderr_contains and stderr_contains not in result.stderr:
                print(
                    f"{name}: expected {expected_exit} got {expected_exit} FAIL "
                    f"(stderr missing {stderr_contains!r})",
                    file=sys.stderr
                )
                print(f"  got: {result.stderr}", file=sys.stderr)
                all_pass = False
                continue

            print(f"{name}: expected {expected_exit} got {expected_exit} OK")

    return 0 if all_pass else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repository root")
    parser.add_argument("--self-test", action="store_true", help="Run self-tests")
    args = parser.parse_args()

    if args.self_test:
        return cmd_self_test()

    try:
        return cmd_render(args.repo_root)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
