#!/usr/bin/env bash
# Aider installer must back up pre-existing AGENTS.md and .aider.conf.yml (issue #256).
# Never runs the installer in the repo root: it writes AGENTS.md into cwd.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)

count_backups() {
  local dir=$1 name=$2
  local found=()
  shopt -s nullglob
  found=("$dir/$name".backup-*)
  shopt -u nullglob
  echo "${#found[@]}"
}

# Case 1: pre-existing files must be backed up
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/proj" "$tmp/home"
printf '# My project AGENTS.md\nHand-written team rules. DO NOT LOSE.\n' > "$tmp/proj/AGENTS.md"
printf 'model: my-model\nauto-commits: false\n' > "$tmp/proj/.aider.conf.yml"
(cd "$tmp/proj" && HOME="$tmp/home" bash "$ROOT/adapters/aider/install.sh" >/dev/null)

n=$(count_backups "$tmp/proj" AGENTS.md)
[[ "$n" -eq 1 ]] || { echo "FAIL: expected exactly 1 AGENTS.md.backup-*, found $n"; exit 1; }
grep -q 'DO NOT LOSE' "$tmp/proj"/AGENTS.md.backup-* || { echo "FAIL: AGENTS.md backup missing original content"; exit 1; }

n=$(count_backups "$tmp/proj" .aider.conf.yml)
[[ "$n" -eq 1 ]] || { echo "FAIL: expected exactly 1 .aider.conf.yml.backup-*, found $n"; exit 1; }
grep -q 'my-model' "$tmp/proj"/.aider.conf.yml.backup-* || { echo "FAIL: .aider.conf.yml backup missing original content"; exit 1; }

grep -q 'Generated by Coco' "$tmp/proj/AGENTS.md" || { echo "FAIL: new AGENTS.md was not written"; exit 1; }
grep -q 'aider.conf' "$tmp/proj/.aider.conf.yml" || { echo "FAIL: new .aider.conf.yml was not written"; exit 1; }

# Case 2: fresh project creates no backups
tmp2=$(mktemp -d)
mkdir -p "$tmp2/proj" "$tmp2/home"
(cd "$tmp2/proj" && HOME="$tmp2/home" bash "$ROOT/adapters/aider/install.sh" >/dev/null)
n=$(count_backups "$tmp2/proj" AGENTS.md)
m=$(count_backups "$tmp2/proj" .aider.conf.yml)
[[ "$n" -eq 0 && "$m" -eq 0 ]] || { echo "FAIL: fresh install created backup files ($n, $m)"; rm -rf "$tmp2"; exit 1; }
rm -rf "$tmp2"

# Case 3: --dry-run writes nothing
tmp3=$(mktemp -d)
mkdir -p "$tmp3/proj" "$tmp3/home"
printf 'original agents\n' > "$tmp3/proj/AGENTS.md"
printf 'original conf\n' > "$tmp3/proj/.aider.conf.yml"
cp "$tmp3/proj/AGENTS.md" "$tmp3/AGENTS.orig"
cp "$tmp3/proj/.aider.conf.yml" "$tmp3/conf.orig"
(cd "$tmp3/proj" && HOME="$tmp3/home" bash "$ROOT/adapters/aider/install.sh" --dry-run >/dev/null)
cmp -s "$tmp3/proj/AGENTS.md" "$tmp3/AGENTS.orig" || { echo "FAIL: --dry-run modified AGENTS.md"; rm -rf "$tmp3"; exit 1; }
cmp -s "$tmp3/proj/.aider.conf.yml" "$tmp3/conf.orig" || { echo "FAIL: --dry-run modified .aider.conf.yml"; rm -rf "$tmp3"; exit 1; }
n=$(count_backups "$tmp3/proj" AGENTS.md)
m=$(count_backups "$tmp3/proj" .aider.conf.yml)
[[ "$n" -eq 0 && "$m" -eq 0 ]] || { echo "FAIL: --dry-run created backup files"; rm -rf "$tmp3"; exit 1; }
rm -rf "$tmp3"

echo "PASS: aider installer backs up existing AGENTS.md and .aider.conf.yml"
