#!/usr/bin/env bash
# `grok/install.sh --uninstall` must remove everything the installer generated (342 SI
# commands, the config.toml MCP block, the hooks file) and nothing the user owns (#267).
# Runs against a temp HOME, with stub binaries so the MCP and hooks steps fire.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
export HOME="$tmp/home"
G="$HOME/.grok"
mkdir -p "$HOME/.coco/bin" "$G/commands" "$G/hooks"
printf '#!/bin/sh\n' | tee "$HOME/.coco/bin/coco-platform-mcp" > "$HOME/.coco/bin/coco-m0-hook"
chmod +x "$HOME/.coco/bin/coco-platform-mcp" "$HOME/.coco/bin/coco-m0-hook"

# User-owned files that must survive: a hand-written SI-named command, a config, another hook.
printf '# my own command\n' > "$G/commands/SI-mine.md"
printf 'model = "mine"\n' > "$G/config.toml"
printf '{}\n' > "$G/hooks/other.json"

bash adapters/grok/install.sh --systems superintelligence >/dev/null
generated=$({ grep -l 'Generated by `build_' "$G"/commands/SI*.md 2>/dev/null || true; } | wc -l | tr -d ' ')
[[ $generated -gt 300 ]] || { echo "FAIL: setup produced only $generated generated SI commands"; exit 1; }
grep -q 'coco:mcp-start' "$G/config.toml" && [[ -f "$G/hooks/coco-m0.json" ]] \
  || { echo "FAIL: setup did not wire the MCP block and hooks"; exit 1; }

bash adapters/grok/install.sh --uninstall >/dev/null

fail=0
bad() { echo "FAIL: $1"; fail=1; }
left=$(grep -l 'Generated by `build_' "$G"/commands/SI*.md 2>/dev/null | wc -l | tr -d ' ' || true)
[[ $left -eq 0 ]] || bad "$left generated SI commands left behind"
[[ -z "$(find "$G" -type l -lname "$ROOT/*")" ]] || bad "symlinks into the clone left behind"
[[ -f "$G/hooks/coco-m0.json" ]] && bad "hooks/coco-m0.json left behind"
grep -q 'coco:' "$G/config.toml" && bad "config.toml still has the coco block"
[[ -f "$G/commands/SI-mine.md" ]] || bad "user's SI-mine.md was deleted"
grep -qx 'model = "mine"' "$G/config.toml" || bad "user's config.toml content was lost"
[[ -f "$G/hooks/other.json" ]] || bad "user's hooks/other.json was deleted"
exit $fail
