#!/usr/bin/env bash
# Aider CLI adapter — generates AGENTS.md and .aider.conf.yml in project root
#
# Usage:
#   bash adapters/aider/install.sh
#   bash adapters/aider/install.sh --systems gsd
#   bash adapters/aider/install.sh --dry-run

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DRY_RUN=0
SYSTEMS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --systems) shift; IFS=',' read -ra SYSTEMS <<< "$1" ;;
    --core-only) CORE_ONLY=1 ;;
    --help|-h) grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done
# --core-only wins over --systems, as in every other adapter.
[[ -z "${CORE_ONLY:-}" ]] || SYSTEMS=()

run() { [[ $DRY_RUN -eq 1 ]] && echo "DRY: $*" || "$@"; }

# Portable sha256 of a file: bare lowercase hex.
sha256_file() {
  local f=$1
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$f" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$f" | awk '{print $1}'
  else
    python3 -c 'import hashlib,sys;print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$f"
  fi
}

# Write a Coco-generated file: header line (printf format, %s = checksum) plus
# body. The checksum covers every byte after the first line, so a later install
# can tell untouched Coco output from user edits (issue #256).
write_generated() {
  local target=$1 fmt=$2 body=$3 tmpbody sum
  tmpbody=$(mktemp)
  printf '%s\n' "$body" > "$tmpbody"
  sum=$(sha256_file "$tmpbody")
  { printf "$fmt\n" "$sum"; cat "$tmpbody"; } > "$target"
  rm -f "$tmpbody"
}

# True when the first line carries our checksum marker and the body still
# hashes to it, i.e. the file is byte-for-byte what Coco last wrote.
is_untouched_coco_output() {
  local f=$1 first expected actual
  IFS= read -r first < "$f" || return 1
  [[ "$first" == *"coco-generated sha256="* ]] || return 1
  expected=${first##*coco-generated sha256=}
  expected=${expected%%[!0-9a-f]*}   # drop any suffix like " -->"
  [[ "$expected" =~ ^[0-9a-f]{64}$ ]] || return 1
  actual=$(tail -n +2 "$f" | sha256_file /dev/stdin)
  [[ "$actual" == "$expected" ]]
}

# Back up a user file before overwriting. The first backup is <file>.coco-backup;
# once that exists it is NEVER overwritten — later backups are timestamped
# copies, then -1, -2, ... until a free name (issue #256).
backup_user_file() {
  local f=$1 b stamp base n=0
  if [[ ! -e "$f.coco-backup" ]]; then
    b="$f.coco-backup"
  else
    stamp=$(date +%Y%m%d-%H%M%S)
    base="$f.coco-backup-$stamp"
    b=$base
    while [[ -e "$b" ]]; do
      n=$((n+1))
      b="$base-$n"
    done
  fi
  cp -p "$f" "$b"
  echo "Backed up existing $f → $b"
}

# Install rule for a generated file (issue #256):
#   absent                    -> write, no backup
#   untouched Coco output     -> overwrite, no backup (checksum still matches)
#   anything else (user text) -> back up first, then write
install_generated() {
  local target=$1 fmt=$2 body=$3
  if [[ -f "$target" ]] && ! is_untouched_coco_output "$target"; then
    backup_user_file "$target"
  fi
  write_generated "$target" "$fmt" "$body"
}

echo "Coco · Aider CLI adapter"
echo "Source: $REPO_ROOT"
echo "Target: $(pwd) (project root)"

# Generate AGENTS.md (body only; checksummed header added by write_generated)
AGENTS_CONTENT="
## Available Agents
"

for agent in "$REPO_ROOT/agents"/*.md; do
  [[ -f "$agent" ]] || continue
  name=$(basename "$agent" .md)
  [[ "$name" == "INDEX" || "$name" == "README" || "$name" == "PROMPT-DEFENSE" ]] && continue
  desc=$(grep -m1 "^description:" "$agent" 2>/dev/null | sed 's/^description: *"*//;s/"*$//' | head -c 120 || true)
  AGENTS_CONTENT+="
### $name
$desc
"
done

# Add system agents if requested
for sys in "${SYSTEMS[@]:-}"; do
  [[ -n "$sys" ]] || continue
  sys_dir="$REPO_ROOT/systems/$sys"
  [[ -d "$sys_dir/agents" ]] || continue
  AGENTS_CONTENT+="
## System: $sys Agents
"
  for a in "$sys_dir/agents"/*.md; do
    [[ -f "$a" ]] || continue
    aname=$(basename "$a" .md)
    adesc=$(grep -m1 "^description:" "$a" 2>/dev/null | sed 's/^description: *"*//;s/"*$//' | head -c 120 || true)
    AGENTS_CONTENT+="
### $aname
$adesc
"
  done
done

if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: write AGENTS.md ($(echo "$AGENTS_CONTENT" | wc -l) lines)"
else
  install_generated AGENTS.md \
    '# AGENTS.md — Generated by Coco for Aider CLI <!-- coco-generated sha256=%s -->' \
    "$AGENTS_CONTENT"
  echo "Wrote: AGENTS.md"
fi

# Generate .aider.conf.yml (body only; checksummed header added by write_generated)
CONF_CONTENT="# See https://aider.chat/docs/config.html for full reference

# Aider has no commit-format option; its default commit messages already
# follow Conventional Commits (<type>: <description>).

# Auto-commits enabled
auto-commits: true

# Read-only files (Coco artifacts — don't modify)
read:
  - AGENTS.md
  - .aider.conf.yml
"

# Add skill references as read-only context
CONF_CONTENT+="
# Coco skills available as context (reference only):
# Skills are in $REPO_ROOT/skills/
# Invoke via /skill-name or ask the agent to use them
"

if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: write .aider.conf.yml"
else
  install_generated .aider.conf.yml \
    '# .aider.conf.yml — Generated by Coco # coco-generated sha256=%s' \
    "$CONF_CONTENT"
  echo "Wrote: .aider.conf.yml"
fi

echo "Done."
